# Generated by Django 2.2.7 on 2019-11-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('feedId', models.AutoField(max_length=15, primary_key=True, serialize=False)),
                ('user1', models.CharField(max_length=25)),
                ('user2', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('messageBlock', models.TextField()),
                ('like', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
