# Generated by Django 2.2.7 on 2019-11-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20191129_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='feedId',
            new_name='messageid',
        ),
    ]
