# Generated by Django 2.2.7 on 2019-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20191129_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageid',
            field=models.AutoField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
