# Generated by Django 2.2.7 on 2019-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191129_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='usernameid',
            field=models.CharField(default='', max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
