# Generated by Django 2.2.7 on 2019-12-05 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191205_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acivate_pass',
            field=models.CharField(default=uuid.UUID('9828293e-1768-11ea-950a-9078418b123e'), max_length=25),
        ),
    ]
