# Generated by Django 2.2.7 on 2019-12-05 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_acivate_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acivate_pass',
            field=models.CharField(default=uuid.UUID('b65eba7f-1768-11ea-a591-9078418b123e'), max_length=100),
        ),
    ]
