# Generated by Django 2.2.7 on 2019-12-05 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191205_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acivate_pass',
        ),
        migrations.AddField(
            model_name='user',
            name='activate_pass',
            field=models.CharField(default=uuid.UUID('32dc598f-176a-11ea-9d65-9078418b123e'), max_length=100),
        ),
    ]
