# Generated by Django 2.2.7 on 2019-12-08 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191205_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activate_pass',
            field=models.CharField(default=uuid.UUID('07372ab0-1983-11ea-a415-9078418b123e'), max_length=100),
        ),
    ]
